---
version: '3'
services:
  broker-1:
    image: confluentinc/cp-kafka:7.3.1
    hostname: broker-1
    container_name: broker-1
    ports:
      - "9091:9091" # for localhost connection
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-1:29092,PLAINTEXT_HOST://localhost:9091
      KAFKA_LISTENERS: PLAINTEXT://broker-1:29092,PLAINTEXT_HOST://localhost:9091,CONTROLLER://broker-1:29093
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093,2@broker-2:29093,3@broker-3:29093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 1000
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/connect-log4j.properties"
    volumes:
      - ./data/kraft/broker-1/data:/tmp/kraft-combined-logs
      - ./kraft/update_run.sh:/tmp/update_run.sh
    env_file:
      - ./kraft/env
    command: "bash -c '/tmp/update_run.sh && /etc/confluent/docker/run'"
    networks:
      kafka-network:
        ipv4_address: 10.6.0.4

  broker-2:
    image: confluentinc/cp-kafka:7.3.1
    hostname: broker-2
    container_name: broker-2
    ports:
      - "9092:9092" # for localhost connection
      - "9102:9101"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-2:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://broker-2:29092,PLAINTEXT_HOST://localhost:9092,CONTROLLER://broker-2:29093
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093,2@broker-2:29093,3@broker-3:29093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 1000
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/connect-log4j.properties"
    volumes:
      - ./data/kraft/broker-2/data:/tmp/kraft-combined-logs
      - ./kraft/update_run.sh:/tmp/update_run.sh
    env_file:
      - ./kraft/env
    command: "bash -c '/tmp/update_run.sh && /etc/confluent/docker/run'"
    networks:
      kafka-network:
        ipv4_address: 10.6.0.5
  
  broker-3:
    image: confluentinc/cp-kafka:7.3.1
    hostname: broker-3
    container_name: broker-3
    ports:
      - "9093:9093" # for localhost connection
      - "9103:9101"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-3:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://broker-3:29092,PLAINTEXT_HOST://localhost:9093,CONTROLLER://broker-3:29093
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093,2@broker-2:29093,3@broker-3:29093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 1000
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/connect-log4j.properties"
    volumes:
      - ./data/kraft/broker-3/data:/tmp/kraft-combined-logs
      - ./kraft/update_run.sh:/tmp/update_run.sh
    env_file:
      - ./kraft/env
    command: "bash -c '/tmp/update_run.sh && /etc/confluent/docker/run'"
    networks:
      kafka-network:
        ipv4_address: 10.6.0.6

 

  # kafdrop:
  #   container_name: kafdrop
  #   image: obsidiandynamics/kafdrop
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     KAFKA_BROKERCONNECT: "broker-1:29092,broker-2:29092,broker-3:29092"
  #     JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
  #   depends_on:
  #     - broker-1
  #     - broker-2
  #     - broker-3
  #   networks:
  #     kafka-network:
  #       ipv4_address: 10.6.0.52

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker-1:29092,broker-2:29092,broker-3:29092
    depends_on:
      - broker-1
      - broker-2
      - broker-3
    networks:
      kafka-network:
        ipv4_address: 10.6.0.51
networks:
  kafka-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
